# Generated by Django 3.2.9 on 2021-11-13 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sto_name', models.CharField(max_length=30, unique=True)),
                ('new_field', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
