# Generated by Django 3.2.9 on 2021-11-13 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_auto_20211113_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='sto',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stos', to='auth.user'),
            preserve_default=False,
        ),
    ]
