# Generated by Django 3.2.9 on 2021-11-23 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20211123_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='sto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sto_reviews', to='website.sto'),
        ),
    ]
