# Generated by Django 3.2.9 on 2021-12-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_review_sto'),
    ]

    operations = [
        migrations.AddField(
            model_name='sto',
            name='status',
            field=models.CharField(default='inactive', max_length=300),
        ),
    ]
